{
    "name": "Pets",
    "summary": "Manage your pets' needs.",
    "category": "Services",
    "author": "Bogosort",
    "website": "https://bogosort.xyz",
    "depends": ["account", "contacts"],
    "data": [
        "views/pets_measurement_views.xml",
        "views/pets_pet_views.xml",
        "views/menu.xml",
        "views/account_move_views.xml",
        "security/ir.model.access.csv",
    ],
    "demo": [],
    "installable": True,
    "application": True,
    "assets": {},
    "license": "Other proprietary",
}
